config/routes.rb
Rails.application.routes.draw do
  root 'repositories#index'

  resources :repositories, only: %i[index new show destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/repository.rb
class Repository < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale

  def set_locale
    cookies[:locale] = params[:locale] if params[:locale]

    return unless cookies[:locale]

    I18n.locale = cookies[:locale] if I18n.locale != cookies[:locale]
  end
end

app/controllers/repositories_controller.rb
class RepositoriesController < ApplicationController
  before_action :set_repository, only: %i[show destroy]

  def index
    @repos = Repository.all.order(:name)
  end

  def show; end

  def new
    failures = 0

    languages.each { |language| failures += 1 unless create_repo(language) }

    if failures.positive?
      flash[:alert] = I18n.t('models.repository.save.failure')
    else
      flash[:notice] = I18n.t('models.repository.save.success')
    end

    redirect_to action: :index
  end

  def destroy
    @repository.destroy

    msg = I18n.t('models.repository.delete.success', repo: @repository.name.capitalize)

    redirect_to root_path, notice: msg
  end

  private

  def create_repo(object)
    repo = Github::Repo.search(object)

    return false if repo.blank?

    save_or_update_repo(repo)
  end

  # rubocop:disable Metrics
  def save_or_update_repo(repo)
    current_tag = Github::Repo.current_tag(repo['tags_url'])
    languages = Github::Repo.get_languages(repo['languages_url'])

    @repository = Repository.find_or_initialize_by(repository_id: repo['id'])
    @repository.name             = repo['name']
    @repository.full_name        = repo['full_name']
    @repository.avatar_url       = repo['owner']['avatar_url']
    @repository.html_url         = repo['html_url']
    @repository.description      = repo['description']
    @repository.current_tag      = current_tag
    @repository.languages        = languages
    @repository.created          = repo['created_at']
    @repository.pushed           = repo['pushed_at']
    @repository.homepage         = repo['homepage']
    @repository.stargazers_count = repo['stargazers_count']
    @repository.watchers_count   = repo['watchers_count']
    @repository.language         = repo['language']
    @repository.license          = repo['license']['name'] if repo['license'].present?
    @repository.save
  end
  # rubocop:enable Metrics

  def set_repository
    @repository = Repository.find(params[:id])
  end

  def languages
    [
      { language: 'python', full_name: 'cpython' }, { language: 'dart', full_name: 'pub' },
      { language: 'typescript', full_name: 'typescript' }, { language: 'ruby', full_name: 'ruby' },
      { language: 'elixir', full_name: 'elixir' }
    ]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def date_br(date_us)
    format_string = english_language ? '%Y-%m-%d' : '%d/%m/%Y'
    date_us.strftime(format_string)
  end

  def english_language
    I18n.locale == :en
  end
end

app/helpers/json_helper.rb
require 'json'

module JsonHelper
  def get_json_keys(hash)
    return [] if hash.blank?

    hash.keys
  end

  def get_percentage(hash, current_key)
    return 0 unless hash.instance_of?(Hash)

    total = hash.values.sum(&:to_i)
    language_value = hash[current_key]
    int_value = language_value / (total / 100)
    rest = language_value % (total / 100)

    "#{int_value}.#{rest}".to_f.round(2)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Featured Repositories</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/repositories/_progress_bar.html.haml
.mb-2
  = language
  %span.fw-bold.fst-italic
    \-
    = percentage
    \%

  .progress
    .progress-bar{ "aria-valuemax": "100", "aria-valuemin": "0", "aria-valuenow": "#{percentage}", role: "progressbar", style: "width: #{percentage}%" }

app/views/repositories/index.html.haml
%main
  .d-flex.justify-content-center.w-100
    - flash.each do |type, message|
      %div{ class: "alert alert-#{ type == 'alert' ? 'danger' : 'success' } alert-dismissible fade show", style: "width: 50rem;", role: "alert" }
        = message
        %button{ type: "button", class: "btn-close", "data-bs-dismiss": "alert", "aria-label": "Close" }
      
  .banner.d-flex.justify-content-center.align-items-center
    .toolbar.d-flex.justify-content-end{ "data-controller": "action" }
      %input{ type: "checkbox", class: "btn-check", id: "btn-check-outlined", autocomplete: "off", checked: english_language, data: { action: "action#language" } }
      %label.btn.btn-outline-light.btn-sm{ for: "btn-check-outlined" }= t('pages.root.buttons.language.text')
    %span
    .content.text-center
      %h1{ class: 'text-white' }= t('pages.root.title')
      %p{ class: 'text-white' }= t('pages.root.subtitle')
      = button_to t('pages.root.buttons.new.text'), new_repository_path, method: :get, class: 'btn btn-outline-light btn-lg', data: { disable_with: t('pages.root.buttons.new.disabled-text') }
    
  .row.d-flex.justify-content-center.mt-65-negative
    .col-11
      .matte-container
        - if @repos.present?
          - @repos.each do |repo|
            = link_to repo, class: "repo-card" do
              .repository-card
                .image.bg-image{ style: "background-image: url(#{repo.avatar_url})" }
                .content
                  %h5.text-uppercase.fw-bold
                    = repo.name
                  %span.text-muted.fs-6.fst-italic.text-max-two-line= repo.full_name
                  %span.fs-6.text-max-two-line= repo.description
        - else
          .text-center.w-100.d-flex.justify-content-center.align-items-center
            %span.fs-5= t('pages.root.empty-list')

app/views/repositories/show.html.haml
%main
  
  .presentation-card
    .d-flex.justify-content-between
      %h4= t('pages.show.title')
      = button_to t('pages.show.buttons.back.text'), root_path, method: :get, class: 'btn btn-outline-dark'

    .row
      .col-12.d-flex.col-header
        .image.bg-image{ style: "background-image: url(#{@repository.avatar_url})" }
        .container-header
          %h5
            %span.fw-bold= t('pages.show.fields.full_name')
            = @repository.full_name

          %h5
            %span.fw-bold= t('pages.show.fields.name')
            %span.text-muted.fst-italic= @repository.name
          
          - if @repository.languages.present?
            %h5
              %span.fw-bold= t('pages.show.fields.languages')
              %div
                - get_json_keys(@repository.languages).each do |language|
                  %span.badge.rounded-pill.bg-dark.mb-1= language
    %hr

    .d-flex.justify-content-between.flex-wrap.mb-3
      %div
        %i.bi.bi-star{ title: t('pages.show.fields.favorite') }
        = @repository.stargazers_count

      %div
        %i.bi.bi-eye{ title: t('pages.show.fields.views') }
        = @repository.watchers_count

      - if @repository.license.present?
        %div
          %i.bi.bi-file-earmark-medical{ title: t('pages.show.fields.license') }
          = @repository.license
      
      - if @repository.current_tag.present?
        %div
          %i.bi.bi-tag{ title: t('pages.show.fields.tag') }
          = @repository.current_tag


    .row.mb-3
      .col-12
        %span.fw-bold= t('pages.show.fields.description')
        = @repository.description
      
      .col-sm-12.col-md-4.col-lg-4
        %span.fw-bold= t('pages.show.fields.language')
        = @repository.language

      .col-sm-12.col-md-4.col-lg-4
        %span.fw-bold= t('pages.show.fields.created')
        = date_br(@repository.created)

      .col-sm-12.col-md-4.col-lg-4
        %span.fw-bold= t('pages.show.fields.pushed')
        = date_br(@repository.pushed)

    .row.mb-3
      - if @repository.languages.present?
        .col-sm-12.col-md-6.col-lg-6
          %h5.fw-bold= t('pages.show.fields.percentage-languages')
          %div
            - get_json_keys(@repository.languages).each do |language|
              = render partial: 'progress_bar',locals: { percentage: get_percentage(@repository.languages, language), language: language }

      .col-sm-12.col-md-6.col-lg-6
        %h5.fw-bold= t('pages.show.docs.title')
        %p
          = t('pages.show.docs.documentation.text')
          - if @repository.homepage.present?
            = link_to t('pages.show.docs.documentation.text-link'), @repository.homepage, target: "_blank"
        %p
          = t('pages.show.docs.repository.text')
          - if @repository.html_url.present?
            = link_to t('pages.show.docs.repository.text-link'), @repository.html_url, target: "_blank"
    
    .row{ "data-controller": "action", "data-action-propt-msg-value": t('pages.show.buttons.delete.msg-propt') }
      .col-12
        %h6= t('pages.show.buttons.delete.description')
        = button_to t('pages.show.buttons.delete.text'), repository_path(@repository.id), method: :delete, class: 'btn btn-outline-danger',
        data: { action: "action#delete" }